### ISSUE TITLE
Crashes gnome-session on install

### ISSUE THREAD

**Issue by BathoryPeter** [pacoqueen/gnome-shell-alarm#4]
When I click the ON/OFF switch on https://extensions.gnome.org/extension/1192/alarm-clock/ and confirm installation, some seconds later gnome-session crashes and drops me to the login screen. I had to delete extension' folder from tty1 to be able to log in gnome session again.
I'm using Ubuntu 17.04 with gnome-session 3.24.0-0ubuntu1.

Please let me know how can I collect some debug information.

**Comment by pacoqueen** [comment]
Thank you for your feedback. Do you have org.gnome.clocks installed?
If so, please, reinstall or activate the extension while running this:
```
sudo journalctl /usr/bin/gnome-shell -f -o cat
```
In some distros, maybe you have to run this instead:
```
sudo journalctl /usr/bin/gnome-session -f -o cat
```

**Comment by BathoryPeter** [comment]
Thanks, installing gnome-clock solved the problem.
Nonetheless, if a missing dependency is able to kill the whole session, it's a critical bug.

**Comment by pacoqueen** [comment]
Sure! I'll try to fix checking for org.gnome.clocks before sending any dbus command. Thanks again for your time.

**Comment by BathoryPeter** [comment]
Ping me if you need some testing.
