### ISSUE TITLE
Applet: Using Gnome Shell Alarm after restart

### ISSUE THREAD

**Issue by lamyergeier** [pacoqueen/gnome-shell-alarm#5]
Could you provide an applet, as then I could automatically start it and it would not be accidentally closed.

**Comment by pacoqueen** [comment]
Sorry but GNOME 3 does not have support for applets anymore. Only extensions.

I think you can restart all extensions, including accidentally closed, by pressing Alt+F2 and typing `r` + `ENTER`.
