### ISSUE TITLE
Countdown timer

### ISSUE THREAD

**Issue by lwbaqueros** [pacoqueen/gnome-shell-alarm#6]
Is it possible to have a countdown timer for the upcoming alarm?

Sometimes it is better to know the time left for the event, rather than the even time itself.

**Comment by pacoqueen** [comment]
Good idea. Maybe on future releases. I'm currently trying to make it work on latest GNOME/gnome-shell on Debian Sid. No clue why stop working. Not having much time for this either by the moment.

I'll keep this issue opened meanwhile.
