### ISSUE TITLE
Gnome clock not detected in Ubuntu 20.04

### ISSUE THREAD

**Issue by stukev** [pacoqueen/gnome-shell-alarm#7]
I've installed the newest gnome-clock but the extension doesn't seem to recognize it. Any ideas?
![image](https://user-images.githubusercontent.com/15886207/96891257-c5b4cb80-1488-11eb-8280-d949cb83ad5d.png)

Gsettings seems to find it just fine:

> gsettings list-recursively | sort | grep clocks
org.gnome.clocks alarms @aa{sv} []
org.gnome.clocks geolocation true
org.gnome.clocks.state.window panel-id 'world'
org.gnome.clocks.state.window size (870, 690)
org.gnome.clocks.state.window state 0
org.gnome.clocks timers [{'duration': <4740>, 'name': <''>}]
org.gnome.clocks world-clocks [{'location': <(uint32 2, <('New York', 'KNYC', true, [(0.71180344078725644, -1.2909618758762367)], [(0.71059804659265924, -1.2916478949920254)])>)>}]

**Comment by stukev** [comment]
Whatever the issue was, it was fixed after a restart. Maybe consider adding this to the readme.

**Comment by pacoqueen** [comment]
Thanks. I'm having issues on latest versions of gnome-shell with some extensions too that are magically solved restarting session or gnome-shell itself (Ctrl+F2, r).

I'll add a Troubleshooting section to the Readme.
